dataset_mapping = {
        'metamath': ("meta-math/MetaMathQA", None, "train", "template.metamathqa"),
        'mmlu': ("cais/mmlu", "all", "auxiliary_train", "template.mmlu"),
        'super_glue/axb': ("aps/super_glue", "axb", "train", "template.axb"),
        'super_glue/boolq': ("aps/super_glue", "boolq", "train", "template.boolq"),
        'super_glue/cb': ("aps/super_glue", "cb", "train", "template.cb"),
        'super_glue/copa': ("aps/super_glue", "copa", "train", "template.copa"),
        'super_glue/multirc': ("aps/super_glue", "multirc", "train", "template.multirc"),
        'super_glue/record': ("aps/super_glue", "record", "train", "template.record"),
        'super_glue/rte': ("aps/super_glue", "rte", "train", "template.rte"),
        'super_glue/wsc': ("aps/super_glue", "wsc", "train", "template.wsc"),
        'super_glue/wic': ("aps/super_glue", "wic", "train", "template.wic"),
        'commonsense_qa': ("tau/commonsense_qa", None, "train", "template.commonsense_qa"),
        'gpqa': ("Idavidrein/gpqa", "gpqa_main,gpqa_extended", "train", "template.gpqa"),
        'gpqa_main': ("Idavidrein/gpqa", "gpqa_main", "train", "template.gpqa"),
        'gpqa_extended': ("Idavidrein/gpqa", "gpqa_extended", "train", "template.gpqa"),
        'gpqa_experts': ("Idavidrein/gpqa", "gpqa_experts", "train", "template.gpqa"),
        }
